framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        headers:
            From: 'ACME <acme@dev.com>'

when@dev:
    framework:
        mailer:
            envelope:
                recipients: ['nono.le.developpeur@gmail.com']
